name: Build, push image and request deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      enable_lint:
        description: "Enable the linting (And format checking) step"
        required: false
        type: boolean
        default: false
      enable_test:
        description: "Enable testing (And building) step"
        required: false
        type: boolean
        default: true
      enable_build:
        description: "Enable the image build step"
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  invoke-top-level:
    name: Invoke Top-Level Pipeline
    if: ${{ github.ref_name == 'main' }}
    uses: dctx-org/cicd-pipelines/.github/workflows/top-level.yml@centralized-v4
    secrets: inherit
    with:
      stack_type: "container"
      environment: ${{ (github.ref_name == 'main' && 'development') }}
      enable_lint: ${{ (github.event_name == 'workflow_dispatch' && inputs.enable_lint) || (github.event_name == 'push' && true) }}
      enable_test: ${{ (github.event_name == 'workflow_dispatch' && inputs.enable_test) || (github.event_name == 'push' && true) }}
      enable_build: ${{ (github.event_name == 'workflow_dispatch' && inputs.enable_build) || (github.ref_name == 'main' && true)  }}
      enable_deploy: false
